Numpy Array স্লাইস করা এবং Broadcasting

In [24]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[0]

np.int64(0)

In [26]:
arr[-1]

np.int64(9)

arr[start::end+1]

In [27]:
yaho=np.arange(20)
yaho

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
yaho[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#jeita theke stat korbo seta 0 index theke 7 index count korbo

In [29]:
yaho[0::6+1]

array([ 0,  7, 14])

index 0 থেকে শুরু
👉 প্রতি 7 ধাপ পর পর সংখ্যা নেবে

🔹 ৪️⃣ Step-by-step দেখি

শুরু index = 0 → মান = 0
0 + 7 = 7 → মান = 7
7 + 7 = 14 → মান = 14
14 + 7 = 21 ❌ (array এর বাইরে, stop)

stoping value ta hobe jei index chai setar value+1

In [30]:
yaho[:7:2]

array([0, 2, 4, 6])

In [31]:
yaho2=yaho[7:17]
yaho2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [32]:
yaho2[4]=99
yaho2

array([ 7,  8,  9, 10, 99, 12, 13, 14, 15, 16])

In [33]:
yaho

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 99, 12, 13, 14, 15, 16,
       17, 18, 19])

main array akn chang hoia gese atake bole array broadcasting,,,,yaho 2 te kaz korle akn chang hoitese yaho array te

In [34]:
yaho2[:]=99
yaho2

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

mane yaho2 ke poro 99 kore disi.ata hoitese array er broadcasting r karone 

In [35]:
yaho

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       17, 18, 19])

numpy array broadcasting array thamanor jonno copy method ase 

In [36]:
yaho3=yaho[3:8].copy()
yaho3

array([ 3,  4,  5,  6, 99])

In [37]:
yaho3[:]=169
yaho3

array([169, 169, 169, 169, 169])

In [38]:
yaho

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       17, 18, 19])

import numpy as np
arr = np.arange(10)

Array হবে:

[0 1 2 3 4 5 6 7 8 9]
1️⃣ Basic slicing
👉 arr[2:6]
[2 3 4 5]

🔥 গুরুত্বপূর্ণ বিষয় (খুবই জরুরি)
NumPy slicing = View (copy না ❗)
arr2 = arr[2:6]
arr2[0] = 100

এখন arr-ও বদলে যাবে 😮

কারণ:
NumPy slice করলে নতুন memory নেয় না — original array-র reference নেয়।যদি copy চাই
arr2 = arr[2:6].copy()

এবার arr2 change করলে original change হবে না।

Matrix স্লাইসিং করা

In [39]:
matrix=np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400],[1000,2000,3000,4000]])

In [40]:
matrix

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

2d array ase jeitar modde 4 ta row ase 4 ta column ase .

In [43]:
third_row[0]

np.int64(100)

In [44]:
matrix[2][2]

np.int64(300)

matrix er 2nd index er 2nd index nicchi

In [45]:
matrix[2,2]

np.int64(300)

akn array ta theke 20,30,200,300 dorkar 1 st ea row golo ke choise korbo ...

In [ ]:
#array([[   1,    2,    3,    4],
       #[  10,   20,   30,   40],
       #[ 100,  200,  300,  400],
       #[1000, 2000, 3000, 4000]])
matrix[1:3, 1:3] #3 likhar karon holo 3 er ag por porjonto jabe but 3 porjonto jabe na  
    

array([[ 20,  30],
       [200, 300]])

1:3 মানে → index 1 থেকে শুরু, index 3 এর আগ পর্যন্ত..তাহলে 1:3 কেন 1 থেকে শুরু?

কারণ slicing এ তুমি নিজে বলে দিচ্ছো কোথা থেকে শুরু করবে।Index 0 → [   1,    2,    3,    4]
Index 1 → [  10,   20,   30,   40]
Index 2 → [ 100,  200,  300,  400]
Index 3 → [1000, 2000, 3000, 4000]

In [51]:
matrix[:,:2]#first 2 columns

array([[   1,    2],
       [  10,   20],
       [ 100,  200],
       [1000, 2000]])

In [52]:
matrix[1:,1:]

array([[  20,   30,   40],
       [ 200,  300,  400],
       [2000, 3000, 4000]])

ei jinista important