In [2]:
print("Assalamualaikum")

Assalamualaikum


In [1]:
print("hello world")

hello world


In [2]:
print("Assalamualaikum")

Assalamualaikum


১️⃣ numpy keno lage বড় সংখ্যার হিসাব দ্রুত করার জন্য

Normal Python list দিয়ে:

a = [1, 2, 3]
b = [4, 5, 6]

এগুলা যোগ করতে loop লাগবে।

কিন্তু NumPy দিয়ে:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

👉 Output: [5 7 9]

✔ Loop লাগলো না
✔ অনেক দ্রুত কাজ করলো

🔹 ২️⃣ Array নিয়ে কাজ করার জন্য

NumPy এর main জিনিস হলো ndarray (N-dimensional array)
মানে 1D, 2D, 3D ডাটা সহজে handle করা যায়।

উদাহরণ:

arr = np.array([[1,2],[3,4]])

এটা একটা matrix।

🔹 ৩️⃣ Machine Learning / Data Science এ দরকার

তুমি যদি ML, Data Science করো —
তাহলে প্রায় সব library (pandas, tensorflow, pytorch, sklearn) NumPy এর উপর কাজ করে।

🔹 ৪️⃣ Mathematical function ready পাওয়া যায়
np.mean()
np.sum()
np.sqrt()
np.sin()

সব built-in আছে।

🎯 সহজ ভাষায়

👉 ছোট কাজের জন্য Python list চলবে
👉 বড় ডাটা / গণিত / ML এর জন্য NumPy লাগে

In [3]:
  import numpy as np
  

In [4]:
np.__version__

'2.4.2'

In [5]:
barry=[1,2,3,4,5]
barry

[1, 2, 3, 4, 5]

In [6]:
narr = np.array(barry)
narr

array([1, 2, 3, 4, 5])

python list ta numpy array te convert hoye gese 

In [7]:
arr_2d=[[1,2,3],[4,5,6],[7,8,9]]
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
narr_2d=np.array(arr_2d)
narr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2d array ke np array convert

np arange method . 

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

zeros method

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

100 bisistto 0 er akta array create holo. 

In [17]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros([3,4,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

3 ta 2d array 4 ta row  proti row te 5 ta kore value ase

ones method

In [19]:
np.ones([3,4,5])


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

np.linspace(start=1,stop=10,num=10)  method

In [21]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

linspace start and ending array dibe mazkhane parthokko same hobe

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Identity matrix method......

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

np.eye return korle akta square matrix return korbe ,,,konAkoni vave same hobe

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random Module,,,,,ata diye random number generate korte pari ...random number er array 2d,3d array generate korte pari.

In [25]:
from numpy import random 

1 ta single random number generate kora jai

In [26]:
np.random.rand()

0.7495055630181684

ata run korle random number dei

In [27]:
np.random.rand(10)

array([0.80500168, 0.13412934, 0.28763768, 0.237566  , 0.12367754,
       0.87613101, 0.4722198 , 0.2924675 , 0.03338857, 0.31334424])

rand method er maddome jei number ei generate kori na keno  obbosoy 0-1 er bitore hobe

unifrom distribution theke newa (rand) jinis ta ki ata self study korte hbe.

In [28]:
np.random.rand(10,5) 

array([[0.11671008, 0.85249278, 0.7064295 , 0.79635195, 0.29151889],
       [0.5004964 , 0.57474486, 0.10120777, 0.58682705, 0.82118549],
       [0.36352762, 0.32537957, 0.72711645, 0.75502894, 0.292664  ],
       [0.23360327, 0.62900949, 0.29347341, 0.09858559, 0.54574268],
       [0.0615813 , 0.00244815, 0.32674232, 0.39320992, 0.1483043 ],
       [0.52979194, 0.73033999, 0.43516483, 0.45129795, 0.39158108],
       [0.45665359, 0.17169758, 0.27514896, 0.91948583, 0.22938228],
       [0.12378833, 0.67173337, 0.04342009, 0.8134837 , 0.53180192],
       [0.54016616, 0.71736335, 0.55009848, 0.29532265, 0.08047407],
       [0.52539225, 0.39453392, 0.89786079, 0.62031167, 0.57015917]])

akn jodi negative number dorkar hoi atar jonno arekta method ase setae holo
np.random.randn method

rand n method ta holo normal distribution ba gausian distribution theke newa ataw self study korte hobe

In [5]:
import numpy as np

np.random.randn()

-1.1255284147180262

Output হতে পারে:

0.54
-1.23
0.08

প্রতিবার রান করলে আলাদা আসবে।

In [16]:
np.random.randn(2,3)

array([[1.30852575, 0.49226355, 0.53765335],
       [0.4496352 , 1.97431117, 1.52736157]])

np.random.randn()
👉 0 কে কেন্দ্র ধরে এলোমেলো সংখ্যা বানায়.......অনেকেই ভাবে এটা 0 থেকে 1 এর মধ্যে থাকবে —
কিন্তু সেটা ভুল ❗

এটা limit ছাড়া distribution....Normal distribution এ:

বেশিরভাগ সংখ্যা থাকবে -1 থেকে +1 এর মধ্যে

কিছু সংখ্যা যাবে -2 থেকে +2

খুব কম ক্ষেত্রে যাবে ±3 এর বাইরে

কিন্তু theoretically সীমা নেই

তাই 1.49 আসা একদম স্বাভাবিক ✅

In [4]:
import numpy as np
np.random.randn(10,2)

array([[ 0.69615239,  0.41693294],
       [-1.09527553, -0.43636349],
       [-2.3531225 ,  0.12740189],
       [-1.21000978,  1.0471107 ],
       [-0.54993258, -0.78849625],
       [ 0.18953837,  0.35880103],
       [-0.38318677, -1.84416051],
       [ 0.06469434, -1.8323454 ],
       [-0.05590215, -0.42720314],
       [-2.04018536,  1.54502637]])

randint method ea integer number generate kore,,,,jekono random number return kore.

In [19]:
np.random.randint(5,10,size=[5,10])

array([[8, 5, 7, 5, 5, 7, 5, 8, 8, 8],
       [5, 8, 7, 6, 8, 8, 6, 6, 7, 7],
       [9, 9, 9, 9, 6, 9, 5, 6, 6, 8],
       [5, 5, 9, 8, 5, 5, 7, 8, 7, 8],
       [5, 9, 6, 8, 7, 9, 5, 7, 6, 9]], dtype=int32)

size er modde onk kiso korte parbo thik ache

In [20]:
np.random.randint(5,10,size=[20,10])

array([[6, 8, 6, 6, 8, 6, 5, 9, 5, 5],
       [6, 5, 9, 5, 6, 7, 9, 8, 8, 7],
       [9, 5, 6, 8, 5, 9, 6, 8, 6, 6],
       [9, 7, 8, 8, 8, 9, 9, 6, 5, 7],
       [7, 9, 9, 6, 5, 9, 6, 9, 5, 8],
       [6, 5, 5, 8, 5, 5, 6, 6, 8, 7],
       [6, 7, 7, 9, 8, 7, 8, 5, 9, 6],
       [9, 8, 6, 7, 9, 8, 9, 5, 8, 6],
       [7, 9, 7, 6, 8, 6, 9, 6, 9, 6],
       [6, 8, 5, 5, 5, 6, 8, 8, 9, 5],
       [5, 6, 9, 5, 8, 9, 9, 8, 6, 5],
       [6, 9, 7, 9, 5, 9, 7, 5, 9, 5],
       [8, 5, 5, 9, 9, 8, 6, 8, 5, 5],
       [6, 8, 9, 7, 9, 5, 9, 6, 8, 8],
       [6, 7, 9, 6, 9, 5, 8, 9, 6, 8],
       [5, 7, 8, 7, 7, 6, 9, 7, 9, 6],
       [7, 9, 6, 7, 8, 9, 5, 9, 6, 9],
       [9, 7, 5, 6, 9, 9, 7, 7, 8, 8],
       [5, 6, 6, 9, 5, 9, 6, 5, 5, 9],
       [6, 7, 7, 5, 6, 8, 5, 9, 5, 5]], dtype=int32)

In [33]:
prb=np.random.randint(5,10,size=[6,3,4])

6 → ৬টা block / প্রথম dimension

3 → প্রতি block-এ ৩টা row

4 → প্রতি row-তে ৪টা column

In [34]:
prb

array([[[7, 6, 9, 7],
        [9, 6, 7, 9],
        [8, 9, 6, 7]],

       [[8, 6, 5, 8],
        [7, 8, 8, 7],
        [9, 9, 9, 8]],

       [[5, 8, 6, 8],
        [7, 7, 7, 6],
        [9, 8, 6, 5]],

       [[8, 9, 7, 5],
        [6, 6, 8, 9],
        [9, 5, 7, 5]],

       [[8, 6, 9, 9],
        [7, 7, 6, 5],
        [8, 6, 9, 6]],

       [[7, 8, 5, 6],
        [5, 7, 9, 5],
        [9, 5, 6, 8]]], dtype=int32)

akta array er shape dimention koto seta easyly ber korar upay holo 

In [43]:
prb.shape

(6, 3, 4)

oporer 3d array ke chaile amra 2d tew convert korte pari,korar jonno sei array er modde koto ta element (6,3,4) ase setar jonno kono change jeno na hoi....mane chailew qmra (12,3) asob ba onno valu dite parbo na.

In [44]:
lala=prb.reshape(12,6)

আমরা জানি মোট element = 72(6,3,4)
তাই reshape করার সময় নতুন shape-এর গুণফলও 72 হতে হবে।মানে প্রতি 6টা block-এর মধ্যে 3টা row, 4টা column ছিল।

এখন reshape করলে হবে:মানে:

6টা row থাকবে

প্রতি row-তে 12টা element থাকবে

অর্থাৎ আগের (3 × 4 = 12) অংশটা এক লাইনে পরিণত হচ্ছে। 

so ata aakta 2d array so 3d ke kibabe element thik rekhe 2d kora jai atai dekhano holo aseusome.

In [40]:
prb

array([[[7, 6, 9, 7],
        [9, 6, 7, 9],
        [8, 9, 6, 7]],

       [[8, 6, 5, 8],
        [7, 8, 8, 7],
        [9, 9, 9, 8]],

       [[5, 8, 6, 8],
        [7, 7, 7, 6],
        [9, 8, 6, 5]],

       [[8, 9, 7, 5],
        [6, 6, 8, 9],
        [9, 5, 7, 5]],

       [[8, 6, 9, 9],
        [7, 7, 6, 5],
        [8, 6, 9, 6]],

       [[7, 8, 5, 6],
        [5, 7, 9, 5],
        [9, 5, 6, 8]]], dtype=int32)

In [45]:
lala

array([[7, 6, 9, 7, 9, 6],
       [7, 9, 8, 9, 6, 7],
       [8, 6, 5, 8, 7, 8],
       [8, 7, 9, 9, 9, 8],
       [5, 8, 6, 8, 7, 7],
       [7, 6, 9, 8, 6, 5],
       [8, 9, 7, 5, 6, 6],
       [8, 9, 9, 5, 7, 5],
       [8, 6, 9, 9, 7, 7],
       [6, 5, 8, 6, 9, 6],
       [7, 8, 5, 6, 5, 7],
       [9, 5, 9, 5, 6, 8]], dtype=int32)

Array theke max and min value khuje ber kora .

In [46]:
lala.max()

np.int32(9)

In [47]:
lala.min()

np.int32(5)

akn 2d array ke 1d array convert

In [57]:
lala=lala.reshape(72)

In [58]:
lala

array([7, 6, 9, 7, 9, 6, 7, 9, 8, 9, 6, 7, 8, 6, 5, 8, 7, 8, 8, 7, 9, 9,
       9, 8, 5, 8, 6, 8, 7, 7, 7, 6, 9, 8, 6, 5, 8, 9, 7, 5, 6, 6, 8, 9,
       9, 5, 7, 5, 8, 6, 9, 9, 7, 7, 6, 5, 8, 6, 9, 6, 7, 8, 5, 6, 5, 7,
       9, 5, 9, 5, 6, 8], dtype=int32)

In [60]:
lala.argmax()

np.int64(2)

mane 2nd index ea big value ta ase 


In [61]:
lala.argmin()

np.int64(14)

14 number index ea min value ase 

In [62]:
lala[14]

np.int32(5)