Conditional সিলেকশন আর Numpy শেষ

aktaa array nibo jei array te condition thakbe 5 theke boro hbr 10 thrkr boro hbee amn kicho jinis pati niay kta hbe

In [4]:
arr=[3,4,5,6,7,8,9,150,225]

In [ ]:
import numpy as np#numpy array te convert 
narr=np.array(arr)
narr

array([  3,   4,   5,   6,   7,   8,   9, 150, 225])

In [16]:
bool_arr =narr>5


boll array ke use kore indexing korte pari

In [13]:
narr[bool_arr] #true golo array dise

array([  6,   7,   8,   9, 150, 225])

In [ ]:
narr[narr>5]#boolean na use koreo same kaj kora jay

array([  6,   7,   8,   9, 150, 225])

In [15]:
narr+narr

array([  6,   8,  10,  12,  14,  16,  18, 300, 450])

In [17]:
narr*2

array([  6,   8,  10,  12,  14,  16,  18, 300, 450])

In [19]:
narrr=np.arange(20)
narrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
narrr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

it vaiyar github repo theke exersize